attn_config:
    embed_dim: 64
    num_heads: 4
    dropout: 0.0
    mlp_hidden_dim: 256
competition_config:
    iters: 2
    use_rnn: False
    update_key: False
sparsification_config:
    type: "bernoulli"                              # "topk", "entmax", "threshold", "bernoulli"
    use_mask_label_final_epoch: 20              # -1 if not using mask labels
    entmax_config:
        alpha_learnable: False
        use_holdout: False
        straight_through: True
        alpha:
            schedule: "linear"              # "constant", "linear", "exponential"
            initial_value: 1.3
            final_value: 1.5
            start_epoch: 10
            final_epoch: 20
    bernoulli_config:
        regularization:
            use_masked_attn_score: False
            use_supervision_loss: False
            threshold: 0.1
            coef:
                schedule: "linear"                  # "constant", "linear", "exponential"
                initial_value: 0.0
                final_value: 0.01
                start_epoch: 10
                final_epoch: 30
    threshold_config:
        threshold: 0.2
        dynamic_threshold: False
        straight_through: True
